#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Math-Base36
Version  : 0.14
Release  : 2
URL      : https://cpan.metacpan.org/authors/id/B/BR/BRICAS/Math-Base36-0.14.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/B/BR/BRICAS/Math-Base36-0.14.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libm/libmath-base36-perl/libmath-base36-perl_0.14-1.debian.tar.xz
Summary  : 'Encoding and decoding of base36 strings'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Math-Base36-man
Requires: perl(Module::Install)
Requires: perl(Sub::Uplevel)
Requires: perl(Test::Exception)
BuildRequires : perl(Module::Install)
BuildRequires : perl(Sub::Uplevel)
BuildRequires : perl(Test::Exception)

%description
NAME
Math::Base36 - Encoding and decoding of base36 strings
SYNOPSIS
use Math::Base36 ':all';

%package man
Summary: man components for the perl-Math-Base36 package.
Group: Default

%description man
man components for the perl-Math-Base36 package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Math-Base36-0.14
mkdir -p %{_topdir}/BUILD/Math-Base36-0.14/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Math-Base36-0.14/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Math/Base36.pm

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Math::Base36.3
